name: GitHub Readme YouTube Cards
on:
  schedule:
    # 23:00 on Sunday.
    - cron: "0 23 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC58SrF1nT13UIHD24oCgFfw
          output_type: html
          readme_path: ./profile/README.md 
